# base image
FROM node:12.2.0-alpine

# set working directory
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY Nib.Career.Web/ClientApp/package*.json ./
RUN npm install --silent 
RUN npm install react-scripts@3.0.1 -g --silent

COPY Nib.Career.Web/ClientApp/ ./

# start app
CMD ["npm", "start"]