version: "3"
services:
  grpc-api:
    build:
      context: .
      dockerfile: Dockerfile.Grpc
    ports:
      - "5110:5110"
    environment:
      ASPNETCORE_URLS: http://+:5110
      ASPNETCORE_ENVIRONMENT: Development
      FILESTORAGEOPTIONS__FILENAME: "jobs.json"
      LOCATIONAPIOPTIONS__HOSTADDRESS: "https://private-8dbaa-nibdevchallenge.apiary-mock.com/location"
  frontend-api:
    build:
      context: .
      dockerfile: Dockerfile.RestApi
    ports:
      - "5120:5120"
    environment:
      ASPNETCORE_URLS: http://+:5120
      ASPNETCORE_ENVIRONMENT: Development
      CAREERGRPCAPIOPTIONS__BASEURL: "http://grpc-api:5110"
    depends_on: ["grpc-api"]
  react:
    build:
      context: .
      dockerfile: Dockerfile.React
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    depends_on: ["grpc-api", "frontend-api"]